services:
  auth-db:
    image: mysql:8.0
    container_name: auth-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
    ports:
      - "3307:3306"
    volumes:
      - auth_db_data:/var/lib/mysql

  project-db:
    image: mysql:8.0
    container_name: project-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_db
    ports:
      - "3308:3306"
    volumes:
      - project_db_data:/var/lib/mysql

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    depends_on:
      - auth-db
    environment:
      DB_HOST: auth-db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: auth_db
      JWT_SECRET: tubes-secret

  workshop-service:
    build: ./workshop-service
    ports:
      - "3005:3002"
    depends_on:
      - project-db
    environment:
      DB_HOST: project-db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: project_db
      JWT_SECRET: tubes-secret

volumes:
  auth_db_data:
  project_db_data:
